### ISSUE TITLE
Unable to install on Ubuntu 22.04?

### ISSUE THREAD

**Issue by layolayo** [silash35/qpdftools#13]
unable to install this on Ubuntu 22.04 as qt5-default is no longer available, is there a workaround?

**Comment by silash35** [comment]
Thank you for letting me know. Currently, I've been putting this project aside, but I'll fix this problem in the next versions.

Until then you can follow the install from source tutorial available on the [Wiki](https://github.com/silash35/qpdftools/wiki/Installation#Installing-from-source).
But instead of installing qt5-default, you install the packages "qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools".

I haven't tested it yet on your Ubuntu version, but I think it still works

**Comment by layolayo** [comment]
Hi Silash35 - yeah that allows installation. working fine using those packages.

Looking forward to an update in the repo

**Comment by silash35** [comment]
Hey, I updated the dependencies and published the new version on the PPA.

See if it works now

**Comment by layolayo** [comment]
silash35 - installs perfectly and runs as expected on 22.04 here. Thank you |
